let flowers =['rose','jasmin','sunflower','lotus'];
checkArray = Array.isArray(flowers);
console.log("its a array? = "+checkArray);
let checkIncludes = flowers.includes('jasmin',0);
console.log("element present ? "+checkIncludes);
flowers.push('lily');
console.log(flowers);
flowers.pop();
console.log(flowers);
let newArray = flowers.unshift('lily');
console.log("the new length of array = "+newArray);
console.log(flowers);
let newArray1 = flowers.shift();
console.log("the deleted element of array = "+newArray1);
console.log(flowers);
let spliceEle = flowers.splice(3,1,'tulip');
console.log("the deleted ele = "+spliceEle);
console.log(flowers);
let tempArray = flowers.slice(0,2);
console.log("temp array = "+tempArray);
console.log(flowers);
let joinEle = flowers.join('-');
console.log("new converted array = "+joinEle);
console.log(flowers);
let index = flowers.indexOf('sunflower');
console.log("element index is = "+index);
